### PR TITLE
Create and drag the View

### PR DESCRIPTION
**Pull request by marijnschilling**
Just a small pull request to check if I'm going in the right direction.

Mostly wandering as to what things should be generically specified in the DateScrubber and what things should be customizable in the client.

Let me know what you think, in the meantime I continue with moving the collectionview according to the DateScrubber position.

### CODE REVIEW

**Comment by 3lvis** [comment]
Might be better if we dropped using CocoaPods for this controller. Is usually nice to have a Podfile and so on only when we have dependencies, otherwise it adds a layer of complexity that we might not need.

**Comment by marijnschilling** [comment]
hmmm, you mean not build the DateScrubber as a pod, but just a class in the demo file? orrr do I misunderstand?

**Comment by 3lvis** [comment]
It's happening!

rere

**Comment by 3lvis** [comment]
🎉

**Pull request merged**
